## **Causas del conflicto**
---

El conflicto es pareto ineficiente: no internalizan el costo del conflicto, political bias (Putin, dictador), assym information, commitment problem.

1. Inexistencia de ejercito mala estimacion de la potencialidad del otro entoncees vamos a conflicto (assymetric info)
2. Commitment problems: USA-China potencia establecida y un rising star, le das ahora paa que una crezca.
3. 

Proxies: cuando empieza el conflicto y luego qué pasa?

UCDP: 

- type of conflict territorial (assym info) /governamental (commit probelm)
- numero de facciones: diferents conflictos que están ocurriendo en el país, guerrillas en colombia
- archivos: UCDP personalist regime
- weak state capacity, gobierno no tiene monopolio de la violencia.


Literature review en classification of conflict by their causes.

In [1]:
import pandas as pd
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.lines as mlines

from utils import plot_style
from utils.plot_helpers import (
    plot_conflict_agreement,
    plot_agreement_mediation_event_studies,
    plot_agreement_mediation_event_studies_conflict,
    plot_agreement_comparison_conflict
)

In [16]:
df_pax = pd.read_csv('../../data/input/pax/pax_data_2144_agreements_v9_10.csv', low_memory=False)
df_pax.columns = df_pax.columns.str.lower()
df_pax = df_pax.rename(columns={"ucdpcon": "conflict_id"})

df_pax["dat"] = pd.to_datetime(df_pax["dat"])
df_pax["year_mo"] = df_pax["dat"].dt.to_period("M").dt.to_timestamp()

#for agreements that involve two countries, stack them into separate rows
df_pax = (
    df_pax
    .set_index([c for c in df_pax.columns if c not in ['loc1iso', 'loc2iso']])
    [['loc1iso', 'loc2iso']]
    .stack()
    .reset_index()
    .drop(columns='level_278')  # removes column indicating loc1/loc2
    .rename(columns={0: 'isocode'})
    
)

# Replace SSD -> SDN before July 2011
mask = (df_pax["isocode"] == "SSD") & (
    (df_pax["dat"].dt.year < 2011) |
    ((df_pax["dat"].dt.year == 2011) & (df_pax["dat"].dt.month <= 6))
)
df_pax.loc[mask, "isocode"] = "SDN"

df_pax = df_pax.dropna(subset=['conflict_id'])
df_pax["conflict_id"] = df_pax["conflict_id"].astype(int)
df_pax

/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()
/var/folders/fz/1mp_qssx1z546qc9z63nq3rm0000gn/T/ipykernel_9925/2191505010.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()

,con,contp,pp,ppname,reg,agtid,ver,agt,dat,status,...,tjrma,tjnr,imun,imoth,imref,impk,ime,imsrc,year_mo,isocode
0,Argentina/United Kingdom,Territory,7,Argentina-UK: Falklands process,Cross-regional,431,1,Joint Statement of Confidence-Building Measure...,1990-02-15,Multiparty signed/agreed,...,0,0,1,1,0,0,1,1,1990-02-01,ARG
1,Argentina/United Kingdom,Territory,7,Argentina-UK: Falklands process,Cross-regional,431,1,Joint Statement of Confidence-Building Measure...,1990-02-15,Multiparty signed/agreed,...,0,0,1,1,0,0,1,1,1990-02-01,GBR
2,Papua New Guinea/(Bougainville),Government/territory,9,Bougainville: peace process,Asia and Pacific,295,1,Agreement to End Hostilities on Bougainville,1990-03-01,Multiparty signed/agreed,...,0,0,0,0,0,0,1,1,1990-03-01,PNG
3,Colombia,Government,97,Colombia I - Gaviria,Americas,168,1,Political Agreement between the National Gover...,1990-03-09,Multiparty signed/agreed,...,0,1,0,1,0,0,1,1,1990-03-01,COL
4,Nicaragua,Government,29,Nicaragua contra process,Americas,589,1,The Toncontin Agreement,1990-03-23,Multiparty signed/agreed,...,1,1,0,1,0,0,1,1,1990-03-01,NIC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2374,Colombia,Government/territory,177,Colombia VII - Petro Peace Dialogues with FARC-EP,Americas,2666,9,Ciclo VI Comunicado Conjunto,2024-10-18,Multiparty signed/agreed,...,0,0,1,1,0,1,1,0,2024-10-01,COL
2375,Israel/Lebanon,Government/territory,64,Israel-Lebanon peace process,Middle East and North Africa,2663,9,Announcement of a Cessation of Hostilities and...,2024-11-26,Multiparty signed/agreed,...,0,0,0,1,0,1,1,0,2024-11-01,LBN
2376,Israel/Lebanon,Government/territory,64,Israel-Lebanon peace process,Middle East and North Africa,2663,9,Announcement of a Cessation of Hostilities and...,2024-11-26,Multiparty signed/agreed,...,0,0,0,1,0,1,1,0,2024-11-01,ISR
2377,Mali/(Azawad),Inter-group,74,Mali-Azawad Inter-Azawad peace process,Africa (excl MENA),2696,9,Pacte d’Honneur pour l’Unite du Peuple de Azawad,2024-11-30,Multiparty signed/agreed,...,0,0,0,0,0,0,0,0,2024-11-01,MLI
2378,South Sudan,Government/territory,107,South Sudan post-secession process,Africa (excl MENA),2715,9,Status of the Tumaini Initiative,2024-12-14,Multiparty signed/agreed,...,0,0,0,1,0,0,0,0,2024-12-01,SSD

In [17]:
df_pax.status.value_counts()

status
Multiparty signed/agreed            1991
Unilateral document                  144
Status unclear                        11
Agreement with subsequent status       7
Name: count, dtype: int64

In [18]:
df_pax.agtp.value_counts()

agtp
Intra         1426
InterIntra     318
IntraLocal     265
Inter          144
Name: count, dtype: int64

In [23]:
df_conflict = pd.read_csv('../../data/output/conflict_level/conflict_panel_semesters.csv', low_memory=False)
conflict_id = df_conflict.conflict_id.unique()
len(conflict_id)

184

In [24]:
#show the conflict_id that are in df_pax
df_pax = df_pax.rename(columns={"ucdpcon": "conflict_id"})

df_pax_filtered = df_pax.loc[df_pax['conflict_id'].isin(conflict_id)]
df_pax_filtered

,con,contp,pp,ppname,reg,agtid,ver,agt,dat,status,...,tjrma,tjnr,imun,imoth,imref,impk,ime,imsrc,year_mo,isocode
2,Papua New Guinea/(Bougainville),Government/territory,9,Bougainville: peace process,Asia and Pacific,295,1,Agreement to End Hostilities on Bougainville,1990-03-01,Multiparty signed/agreed,...,0,0,0,0,0,0,1,1,1990-03-01,PNG
3,Colombia,Government,97,Colombia I - Gaviria,Americas,168,1,Political Agreement between the National Gover...,1990-03-09,Multiparty signed/agreed,...,0,1,0,1,0,0,1,1,1990-03-01,COL
4,Nicaragua,Government,29,Nicaragua contra process,Americas,589,1,The Toncontin Agreement,1990-03-23,Multiparty signed/agreed,...,1,1,0,1,0,0,1,1,1990-03-01,NIC
5,Guatemala,Government,45,Guatemala peace process,Americas,309,1,Basic Agreement for the Search for Peace by Po...,1990-03-30,Multiparty signed/agreed,...,0,1,0,0,0,0,1,1,1990-03-01,GTM
6,Costa Rica/El Salvador/Guatemala/Honduras/Nica...,Government,29,Nicaragua contra process,Americas,887,1,Montelimar Declaration,1990-04-03,Multiparty signed/agreed,...,0,1,0,0,0,1,0,1,1990-04-01,NIC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2374,Colombia,Government/territory,177,Colombia VII - Petro Peace Dialogues with FARC-EP,Americas,2666,9,Ciclo VI Comunicado Conjunto,2024-10-18,Multiparty signed/agreed,...,0,0,1,1,0,1,1,0,2024-10-01,COL
2375,Israel/Lebanon,Government/territory,64,Israel-Lebanon peace process,Middle East and North Africa,2663,9,Announcement of a Cessation of Hostilities and...,2024-11-26,Multiparty signed/agreed,...,0,0,0,1,0,1,1,0,2024-11-01,LBN
2376,Israel/Lebanon,Government/territory,64,Israel-Lebanon peace process,Middle East and North Africa,2663,9,Announcement of a Cessation of Hostilities and...,2024-11-26,Multiparty signed/agreed,...,0,0,0,1,0,1,1,0,2024-11-01,ISR
2377,Mali/(Azawad),Inter-group,74,Mali-Azawad Inter-Azawad peace process,Africa (excl MENA),2696,9,Pacte d’Honneur pour l’Unite du Peuple de Azawad,2024-11-30,Multiparty signed/agreed,...,0,0,0,0,0,0,0,0,2024-11-01,MLI
2378,South Sudan,Government/territory,107,South Sudan post-secession process,Africa (excl MENA),2715,9,Status of the Tumaini Initiative,2024-12-14,Multiparty signed/agreed,...,0,0,0,1,0,0,0,0,2024-12-01,SSD

In [31]:
df_pax_filtered.conflict_id.nunique()

100

In [25]:
df_pax_filtered.agtp.value_counts()

agtp
Intra         1392
InterIntra     302
IntraLocal     263
Inter          104
Name: count, dtype: int64

In [27]:
df_pax_filtered.groupby('agtp')['conflict_id'].nunique()

agtp
Inter         13
InterIntra    39
Intra         85
IntraLocal    19
Name: conflict_id, dtype: int64